=== mikecurtis1/Semantic_XML/src/sonnet29.dtd
<!ELEMENT document (sonnet+)>
	<!ELEMENT sonnet (title, quatrain, quatrain, quatrain, couplet, author)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT quatrain (line, line, line, line)>
		<!ELEMENT couplet (line, line)>
			<!ELEMENT line (#PCDATA|first_word|rhyme)*>
				<!ELEMENT first_word (#PCDATA)>
				<!ELEMENT rhyme (#PCDATA)>
		<!ELEMENT author (name,date)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT date (#PCDATA)>
<!ATTLIST quatrain number (1|2|3) #REQUIRED>
<!ATTLIST line number (1|2|3|4) #REQUIRED>
<!ATTLIST rhyme scheme (A|B|C|D|E|F|G) #REQUIRED type (perfect|near) #REQUIRED cadence (antecedent|consequent) #REQUIRED>

=== mikecurtis1/Semantic_XML/src/sonnet29.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="sonnet29.css"?>
<!DOCTYPE document SYSTEM "sonnet29.dtd">
<document>
  <sonnet>
	<title>Sonnet XXIX</title>
	<quatrain number="1">
		<line number="1"><first_word>When</first_word> in disgrace with fortune and men's e<rhyme scheme="A" type="perfect" cadence="antecedent">yes</rhyme>,</line>
		<line number="2">I all alone beweep my outcast st<rhyme scheme="B" type="perfect" cadence="antecedent">ate</rhyme>,</line>
		<line number="3">And trouble deaf heaven with my bootless cr<rhyme scheme="A" type="perfect" cadence="consequent">ies</rhyme>,</line>
		<line number="4">And look upon myself, and curse my f<rhyme scheme="B" type="perfect" cadence="consequent">ate</rhyme>;</line>
	</quatrain>
	<quatrain number="2">
		<line number="1">Wishing me like to one more rich in h<rhyme scheme="C" type="perfect" cadence="antecedent">ope</rhyme>,</line>
		<line number="2">Featur'd like him, like him with friends poss<rhyme scheme="D" type="near" cadence="antecedent">ess'd</rhyme>,</line>
		<line number="3">Desiring this man's art, and that man's sc<rhyme scheme="C" type="perfect" cadence="consequent">ope</rhyme>,</line>
		<line number="4">With what I most enjoy contented l<rhyme scheme="D" type="near" cadence="consequent">east</rhyme>;</line>
	</quatrain>
	<quatrain number="3">
		<line number="1">Yet in these thoughts my self almost desp<rhyme scheme="E" type="perfect" cadence="antecedent">ising</rhyme>,</line>
		<line number="2">Haply I think on thee,-- and then my st<rhyme scheme="F" type="perfect" cadence="antecedent">ate</rhyme>,</line>
		<line number="3">Like to the lark at break of day ar<rhyme scheme="E" type="perfect" cadence="consequent">ising</rhyme>,</line>
		<line number="4">From sullen earth, sings hymns at heaven's g<rhyme scheme="F" type="perfect" cadence="consequent">ate</rhyme>;</line>
	</quatrain>
	<couplet>
		<line number="1">For thy sweet love remember'd such wealth br<rhyme scheme="G" type="perfect" cadence="antecedent">ings</rhyme>,</line>
		<line number="2">That then I scorn to change my state with k<rhyme scheme="G" type="perfect" cadence="consequent">ings</rhyme>.</line>
	</couplet>
	<author>
		<name>William Shakespeare</name>
		<date>(1564-1616)</date>
	</author>
  </sonnet>
</document>
